### ISSUE TITLE
Bootstrap portfolio project review :

### ISSUE THREAD

**Issue by tajulafreen** [tajulafreen/Bootstrap-Portfolio#2]
Hi everyone the issue is open and give some suggestions for my project.

**Comment by norbiboy1** [comment]
Hi Mrs. @tajulafreen.

You had a very good job implementing the bootstrap project. Still seen some requirements to be change ♻️ 💯 😃 
For the desktop version: 👍 
 - Kindly fix the navigation menu with anchor lists <a></a>
 - Implement effects for the buttons, :active and :hover effect
 - Put the background images to the desktop version
 - For the technologies section you don't need to use again recent works cards.

For the mobile version: 👍 
 - Kindly add effect to the hamburger menu
 - Delete on the technologies section the recent works cards.

✅ Thank you for distributing your project. 
You did a really good job 😄

**Comment by Pi1998** [comment]
Hi @tajulafreen  , 

# STATUS: APPROVED 🟢

Your project is complete!  :shipit: 
Congratulations! 🎉 

>## TO HIGHLIGHT: 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

> ## Optional suggestions
✅ I think it's more appropriate if you change the color of the text according to the template by adding `text-dark`.

> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Obimbo07** [comment]
Hello @tajulafreen

**Comment by Obimbo07** [comment]
Hello @tajulafreen 
 ### STATUS APPROVED 🟢
Your project is complete!✨
Congratulations! 🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif). 

## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* All Linters Passing  :heavy_check_mark: 
* Good PR  Title & summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.
